import React from 'react';
import PageLayout from '../layout/PageLayout';

const PrivacyPolicy = ({ onLoginClick }) => {
    return (
        <PageLayout onLoginClick={onLoginClick}>
            <div className="container mx-auto px-4 max-w-3xl">
                <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
                <div className="prose dark:prose-invert prose-lg">
                    <p className="lead">Last updated: {new Date().toLocaleDateString()}</p>
                    <p>
                        At iMentor, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our AI mentoring platform.
                    </p>
                    <h3>1. Information We Collect</h3>
                    <p>
                        We collect information that you strictly provide to us when you register for an account, such as your name, email address, and academic interests. We also collect data generated by your interactions with our AI models to improve your learning experience.
                    </p>
                    <h3>2. How We Use Your Information</h3>
                    <p>
                        We use the information we collect to:
                    </p>
                    <ul>
                        <li>Provide, operate, and maintain our website and services.</li>
                        <li>Improve, personalize, and expand our website and services.</li>
                        <li>Understand and analyze how you use our website and services.</li>
                        <li>Develop new products, services, features, and functionality.</li>
                    </ul>
                    <h3>3. Data Security</h3>
                    <p>
                        We implement appropriate technical and organizational security measures to protect your data. Your academic data and chat history are encrypted and stored securely.
                    </p>
                    <h3>4. Contact Us</h3>
                    <p>
                        If you have any questions about this Privacy Policy, please contact us at privacy@imentor.ai.
                    </p>
                </div>
            </div>
        </PageLayout>
    );
};

export default PrivacyPolicy;
